### ISSUE TITLE
Commands to read and bump Version numbers

### ISSUE THREAD

**Issue by andersonlucasg3** [andersonlucasg3/buildcannon#6]
## Tasks:
- [ ] Create `project-info` command;
- [ ] Create `--version` parameter;
- [ ] Create `--build` parameter;
